project_id = "zyymtlumobchllixfadm"

[functions.analyze-interviews]
verify_jwt = false

[functions.generate-fiche-action]
verify_jwt = false

[functions.pinecone-search]
verify_jwt = false

[functions.doc-synthesis]
verify_jwt = false

[functions.ingest-documents]
verify_jwt = false

[functions.import-finess]
verify_jwt = false

[functions.import-has-certification]
verify_jwt = false

[functions.import-population]
verify_jwt = false
